# Generated by Django 5.0.4 on 2024-07-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
